#!/bin/bash

# Converts Zotero-produced json bib file into html and csv

# Set up some variables
me=$USER
dest="/Users/$me/Documents/github/local/temples"
temp=$(echo $TMPDIR | sed 's:/$::')

# Path to include homebrew stuff like pandoc for running via launchctl
export PATH="/opt/homebrew/bin:$PATH"

# Convert the json file to html directly.
# pandoc -f csljson "$dest/temple_bib.json" --citeproc -s -o  "$dest/temple_bib.html" --metadata title="Bibliography for temple database"
temple_bib_html=$(pandoc -f csljson "$dest/temple_bib.json" --citeproc -s --metadata title="Bibliography for temple database" 2>&1)

# Make sure that it went ok before proceeding
if [ $? -ne 0 ]
	then
	echo "$(date +%Y-%m-%d\ %H:%M:%S) bib2html: " $temple_bib_html 1>&2
	exit 0
fi

if [ ${temple_bib_html:0:6} == 'pandoc' ]
	then
	echo "$(date +%Y-%m-%d\ %H:%M:%S) bib2html: No references generated by pandoc-citeproc" 1>&2
	exit 0
fi

# Make sure something has changed or else exit
if [ -s "$dest/temple_bib.html" ]
then
	htmlsum=`echo "$temple_bib_html" | md5`
	filesum=`md5 -q "$dest/temple_bib.html"`
	if [ $htmlsum = $filesum ]
	then
	   echo "$(date +%Y-%m-%d\ %H:%M:%S) bib2html: No change to temple bibliography." 1>&2
	   exit 0
	fi
fi

# Save to file
echo "$temple_bib_html" > "$dest/temple_bib.html"

# Also generate a simple csv with key and citation strings in plain text and html
csv=`grep 'div id="ref-' "$dest/temple_bib.html" | perl -pe 's/^.*ref\-(.+?)\".*$/\1/' | perl -pe 's/ /\n\n/g' | perl -pe 's/(.+)/\1, @\1/g'`

# Run this through pandoc, once for each format
# Feed pandoc a modified chicago-style csl where the citation is replaced by the bibliography
# Plain text
plain=`echo "$csv" | pandoc --citeproc --wrap=preserve --bibliography=$dest/temple_bib.json --csl=$dest/chicago-author-date.csl -t plain | perl -pe 's/^([^\s]+? )/"\1"/' | perl -pe 's/,\s/",/' | perl -pe 's/(.)\.(\”)*$/\1\2"/'`

# HTML
html=`echo "$csv" | pandoc --citeproc --wrap=preserve --bibliography=$dest/temple_bib.json --csl=$dest/chicago-author-date.csl -t html | perl -pe 's/<(p|\/p)>//' | perl -pe 's/<span class=.*?>//g' | perl -pe 's/"/\\\"/g' | perl -pe 's/^.+?,\s/"/' | perl -pe 's/<\/span>$/"/' | perl -pe 's/\."$/"/g'`

# Combine two formats into final output format and save to file
paste -d , <(printf %s "$plain") <(printf %s "$html") > "$dest/bibliography.csv"

# Check the output to make sure all items in Zotero are appearing

# Search it all & generate list in one go
result=`for i in $(csvcut -c 3 "$dest/citations.csv"); do echo -en "$i\t"; grep -c "$i" "$dest/temple_bib.json"; done | grep "\t0" | sort | uniq | perl -pe 's/\t0$//' | perl -pe 's/\n/, /' | sed 's/, $//'`

if [[ -n $result ]]
then
  err="$(date +%Y-%m-%d\ %H:%M:%S) The following citations appear in the citations.csv, but not in the bibliography outputted from Zotero:"
  echo $err "$result" 1>&2
else
  echo "$(date +%Y-%m-%d\ %H:%M:%S) No missing citations" 1>&2
fi
