#!/bin/bash

# Converts Zotero-produced json bib file into html

# Set up some variables
me=$(whoami)
dest="/Users/$me/Documents/github/local/temples"
temp=$(echo $TMPDIR | sed 's:/$::')

# Path to include homebrew stuff like pandoc for running via launchctl
export PATH="/usr/local/bin:$PATH"

# Convert the json file to html directly.
bib=`pandoc -f csljson "$dest/temple_bib_general.json" --citeproc`

if [ -f "$dest/temple_bib_general.html" ]
then
  bibdiff=$(diff "$dest/temple_bib_general.html" <(echo "$bib"))
  if [ ${#bibdiff} == 0 ]
  then
	echo "$(date +%Y-%m-%d\ %H:%M:%S) No change to general temple bibliography." 1>&2
	exit 0
  else
	echo "$bib" > $dest/temple_bib_general.html
  fi
fi

# Make sure that it went ok before proceeding
if [ $? -ne 0 ]
	then
	echo "$(date +%Y-%m-%d\ %H:%M:%S) general bibliography updated" 1>&2
	exit
fi
if [ ! $(stat -f %z "$dest/temple_bib_general.html")  ]
	then
	echo "$(date +%Y-%m-%d\ %H:%M:%S) No general references generated by pandoc-citeproc" 1>&2
	exit
fi
